---

- name: Download jenkins base image
  docker_image:
          name: jenkins/jenkins
          source: pull
  notify:
          - build_automated_jenkins_image

- name: Ensure docker build dir
  file:
          dest: "{{ jenkins_build_dir }}"
          state: directory
          mode: '0666'
 
- name: Copy dockerfile
  template:
          src: Dockerfile.j2
          dest: "{{ jenkins_build_dir }}/Dockerfile"
          mode: '0644'
  notify:
          - build_automated_jenkins_image

- name: copy jenkins cac
  template:
          src: "{{ jenkins_config_file }}"
          dest: "{{ jenkins_build_dir }}/jenkins.yaml"
          mode: '0644'
  notify:
          - build_automated_jenkins_image

